services:
  nginx:
    network_mode: host
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  frontend:
    pull_policy: always
    image: ghcr.io/cndss25/frontend:latest
    ports:
      - 3000:3000