services:
  nginx:
    network_mode: host
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

#  rabbitmq:
#    image: rabbitmq:3-management
#    restart: unless-stopped
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics -q ping
#      interval: 15s
#      timeout: 30s
#      retries: 5

  frontend:
    pull_policy: always
    image: ghcr.io/cndss25/frontend:latest
    ports:
      - "3000:3000"
    environment:
      user_service_url: ${USER_SERVICE_URL}
      property_service_url: ${PROPERTY_SERVICE_URL}
      stock_service_url: ${STOCK_SERVICE_URL}
      dashboard_service_url: ${DASHBOARD_SERVICE_URL}

  user-service:
    pull_policy: always
    image: ghcr.io/cndss25/user-service:latest
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: ${MONGODB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  property-service:
    pull_policy: always
    image: ghcr.io/cndss25/property-service:latest
    ports:
      - "8001:8001"
    environment:
      MONGODB_URL: ${MONGODB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

#  stock-service:
#    pull_policy: always
#    image: ghcr.io/cndss25/stock-service:latest
#    ports:
#      - "8002:8002"
#    environment:
#      MONGODB_URL: ${MONGODB_URL}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
#
#  dashboard-service:
#    pull_policy: always
#    image: ghcr.io/cndss25/dashboard-service:latest
#    ports:
#      - "8003:8003"
#    environment:
#      MONGODB_URL: ${MONGODB_URL}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}